[build]
  publish = "client/build"
  command = "cd client && npm install && npm run build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[dev]
  command = "npm run dev"
  port = 8888

[functions]
  directory = "netlify/functions"

[build.environment]
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true" 
  GENERATE_SOURCEMAP = "false"

[context.production.environment]
  REACT_APP_API_URL = ""
  REACT_APP_USE_FIREBASE_AUTH = "true"
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Do not force the redirect; let Netlify serve existing static files first
