# Disabled workflow - using manual Netlify CLI deployment
name: Disabled Deploy

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
    - name: Workflow Disabled
      run: echo "This workflow is disabled. Using manual Netlify CLI deployment instead."